# Generated by Django 6.0.4 on 2026-04-16 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrosurFakultas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_fakultas', models.CharField(max_length=10)),
                ('nama_fakultas', models.CharField(max_length=200)),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='brosur/')),
                ('file_pdf', models.FileField(blank=True, null=True, upload_to='brosur/pdf/')),
                ('deskripsi', models.TextField(blank=True)),
                ('link_video', models.URLField(blank=True, help_text='Link video YouTube profil fakultas')),
                ('urutan', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('tgl_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Brosur Fakultas',
                'verbose_name_plural': 'Brosur Fakultas',
                'db_table': 'pmb"."brosur_fakultas',
                'ordering': ['urutan', 'nama_fakultas'],
            },
        ),
        migrations.CreateModel(
            name='DokumenDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='download/')),
                ('ukuran', models.CharField(blank=True, max_length=20)),
                ('urutan', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('tgl_upload', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dokumen Download',
                'verbose_name_plural': 'Dokumen Download',
                'db_table': 'pmb"."dokumen_download',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pertanyaan', models.CharField(max_length=500)),
                ('jawaban', models.TextField()),
                ('kategori', models.CharField(choices=[('umum', 'Umum'), ('biaya', 'Biaya & Pembayaran'), ('jadwal', 'Jadwal & Gelombang'), ('dokumen', 'Dokumen Persyaratan'), ('seleksi', 'Seleksi & Tes'), ('daftar_ulang', 'Daftar Ulang'), ('beasiswa', 'Beasiswa'), ('prodi', 'Program Studi')], default='umum', max_length=15)),
                ('urutan', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQ',
                'db_table': 'pmb"."faq',
                'ordering': ['kategori', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='GaleriKampus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='galeri/')),
                ('link_video', models.URLField(blank=True, help_text='Link video YouTube (opsional)')),
                ('kategori', models.CharField(choices=[('gedung', 'Gedung & Fasilitas'), ('kegiatan', 'Kegiatan Mahasiswa'), ('fasilitas', 'Fasilitas Kampus'), ('prestasi', 'Prestasi'), ('wisuda', 'Wisuda')], default='kegiatan', max_length=15)),
                ('urutan', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
            ],
            options={
                'verbose_name': 'Galeri Kampus',
                'verbose_name_plural': 'Galeri Kampus',
                'db_table': 'pmb"."galeri_kampus',
                'ordering': ['urutan', 'judul'],
            },
        ),
        migrations.CreateModel(
            name='MediaSosial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('tiktok', 'TikTok'), ('twitter', 'Twitter / X'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=15)),
                ('nama_akun', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('urutan', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
            ],
            options={
                'verbose_name': 'Media Sosial',
                'verbose_name_plural': 'Media Sosial',
                'db_table': 'pmb"."media_sosial',
                'ordering': ['urutan'],
            },
        ),
        migrations.CreateModel(
            name='MitraKerjasama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mitra', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='mitra/')),
                ('website', models.URLField(blank=True)),
                ('keterangan', models.TextField(blank=True)),
                ('urutan', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
            ],
            options={
                'verbose_name': 'Mitra Kerjasama',
                'verbose_name_plural': 'Mitra Kerjasama',
                'db_table': 'pmb"."mitra_kerjasama',
                'ordering': ['urutan', 'nama_mitra'],
            },
        ),
        migrations.CreateModel(
            name='Pengumuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=300)),
                ('isi', models.TextField()),
                ('file_lampiran', models.FileField(blank=True, null=True, upload_to='pengumuman/')),
                ('tgl_tayang', models.DateField()),
                ('tgl_selesai', models.DateField(blank=True, null=True)),
                ('penting', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pengumuman',
                'verbose_name_plural': 'Pengumuman',
                'db_table': 'pmb"."pengumuman',
                'ordering': ['-penting', '-tgl_tayang'],
            },
        ),
        migrations.CreateModel(
            name='Testimoni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('prodi', models.CharField(max_length=200)),
                ('angkatan', models.CharField(max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='testimoni/')),
                ('isi_testimoni', models.TextField()),
                ('urutan', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
            ],
            options={
                'verbose_name': 'Testimoni',
                'verbose_name_plural': 'Testimoni',
                'db_table': 'pmb"."testimoni',
                'ordering': ['urutan'],
            },
        ),
    ]
