# Generated by Django 6.0.4 on 2026-04-17 06:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pendaftaran', '0004_profilpendaftar_ukuran_baju'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateNotifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('trigger', models.CharField(choices=[('registrasi', 'Setelah Registrasi'), ('aktivasi', 'Setelah Aktivasi Email'), ('profil_lengkap', 'Profil Lengkap'), ('dokumen_upload', 'Dokumen Diupload'), ('dokumen_acc', 'Dokumen Diverifikasi'), ('dokumen_tolak', 'Dokumen Ditolak'), ('terjadwal', 'Terjadwal Seleksi'), ('lulus_seleksi', 'Lulus Seleksi'), ('tidak_lulus', 'Tidak Lulus Seleksi'), ('daftar_ulang', 'Pengingat Daftar Ulang'), ('pembayaran', 'Konfirmasi Pembayaran'), ('manual', 'Kirim Manual')], max_length=20, unique=True)),
                ('jenis', models.CharField(choices=[('email', 'Email'), ('whatsapp', 'WhatsApp'), ('both', 'Email & WhatsApp')], default='both', max_length=10)),
                ('subjek_email', models.CharField(blank=True, max_length=200)),
                ('isi_email', models.TextField(blank=True, help_text='Gunakan {{nama}}, {{no_pendaftaran}}, {{prodi}}, {{jalur}}, {{status}}')),
                ('isi_wa', models.TextField(blank=True, help_text='Pesan WhatsApp. Gunakan {{nama}}, {{no_pendaftaran}}, dst')),
                ('aktif', models.BooleanField(default=True)),
                ('tgl_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Template Notifikasi',
                'verbose_name_plural': 'Template Notifikasi',
                'db_table': 'pmb"."template_notifikasi',
            },
        ),
        migrations.CreateModel(
            name='LogNotifikasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(max_length=10)),
                ('tujuan', models.CharField(help_text='Email atau nomor WA', max_length=200)),
                ('subjek', models.CharField(blank=True, max_length=200)),
                ('isi', models.TextField()),
                ('status', models.CharField(choices=[('terkirim', 'Terkirim'), ('gagal', 'Gagal'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('error_msg', models.TextField(blank=True)),
                ('tgl_kirim', models.DateTimeField(auto_now_add=True)),
                ('pendaftaran', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifikasi', to='pendaftaran.pendaftaran')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifikasi.templatenotifikasi')),
            ],
            options={
                'verbose_name': 'Log Notifikasi',
                'verbose_name_plural': 'Log Notifikasi',
                'db_table': 'pmb"."log_notifikasi',
                'ordering': ['-tgl_kirim'],
            },
        ),
    ]
