# Generated by Django 6.0.4 on 2026-04-16 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('pendaftaran', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DokumenPendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(blank=True, null=True, upload_to='dokumen_pendaftar/')),
                ('link_drive', models.URLField(blank=True, help_text='Alternatif link Google Drive')),
                ('status_verifikasi', models.CharField(choices=[('belum', 'Belum Diupload'), ('menunggu', 'Menunggu Verifikasi'), ('terverifikasi', 'Terverifikasi'), ('ditolak', 'Ditolak')], default='menunggu', max_length=15)),
                ('catatan_verifikasi', models.TextField(blank=True)),
                ('tgl_upload', models.DateTimeField(auto_now_add=True)),
                ('tgl_verifikasi', models.DateTimeField(blank=True, null=True)),
                ('diverifikasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dokumen_diverifikasi', to=settings.AUTH_USER_MODEL)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dokumen', to='pendaftaran.pendaftaran')),
                ('persyaratan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.persyaratanjalur')),
            ],
            options={
                'verbose_name': 'Dokumen Pendaftar',
                'verbose_name_plural': 'Dokumen Pendaftar',
                'db_table': 'pmb"."dokumen_pendaftar',
                'ordering': ['persyaratan__urutan'],
                'unique_together': {('pendaftaran', 'persyaratan')},
            },
        ),
    ]
