# Generated by Django 6.0.4 on 2026-04-16 07:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanChatbot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bot', models.CharField(default='SINTA', max_length=100)),
                ('deskripsi_bot', models.CharField(default='Asisten PMB UNISAN', max_length=200)),
                ('foto_bot', models.ImageField(blank=True, null=True, upload_to='chatbot/')),
                ('pesan_sambutan', models.TextField(default='Halo! Saya SINTA, asisten virtual PMB UNISAN. Ada yang bisa saya bantu?')),
                ('pesan_fallback', models.TextField(default='Maaf, saya belum bisa menjawab pertanyaan itu. Silakan hubungi panitia PMB.')),
                ('pesan_eskalasi', models.TextField(default='Pertanyaan Anda akan diteruskan ke panitia PMB. Silakan tunggu.')),
                ('ai_provider', models.CharField(choices=[('claude', 'Anthropic Claude'), ('openai', 'OpenAI GPT')], default='claude', max_length=10)),
                ('ai_model', models.CharField(default='claude-sonnet-4-6', max_length=50)),
                ('system_prompt', models.TextField(blank=True)),
                ('max_token', models.IntegerField(default=500)),
                ('aktif', models.BooleanField(default=True)),
                ('jam_operasional', models.CharField(choices=[('24jam', 'Aktif 24 Jam'), ('jam_tertentu', 'Jam Tertentu')], default='24jam', max_length=15)),
                ('jam_buka', models.TimeField(blank=True, null=True)),
                ('jam_tutup', models.TimeField(blank=True, null=True)),
                ('pesan_diluar_jam', models.TextField(default='Chatbot sedang tidak aktif. Silakan hubungi panitia PMB.')),
            ],
            options={
                'verbose_name': 'Pengaturan Chatbot',
                'verbose_name_plural': 'Pengaturan Chatbot',
                'db_table': 'pmb"."pengaturan_chatbot',
            },
        ),
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('jalur', 'Jalur Penerimaan'), ('biaya', 'Biaya & Pembayaran'), ('jadwal', 'Jadwal & Gelombang'), ('dokumen', 'Dokumen Persyaratan'), ('seleksi', 'Seleksi & Tes'), ('prodi', 'Program Studi'), ('fasilitas', 'Fasilitas Kampus'), ('kontak', 'Kontak PMB'), ('cara_daftar', 'Cara Mendaftar'), ('referral', 'Referral & Afiliasi'), ('rpl', 'Jalur RPL'), ('umum', 'Informasi Umum')], default='umum', max_length=15)),
                ('pertanyaan', models.TextField(help_text='Contoh pertanyaan yang memicu jawaban ini')),
                ('kata_kunci', models.TextField(help_text='Kata kunci trigger, pisah dengan koma')),
                ('jawaban', models.TextField(help_text='Jawaban yang sudah disiapkan admin')),
                ('link_terkait', models.URLField(blank=True, help_text='Link halaman yang relevan')),
                ('urutan_prioritas', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('tgl_update', models.DateTimeField(auto_now=True)),
                ('diupdate_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge Base',
                'verbose_name_plural': 'Knowledge Base',
                'db_table': 'pmb"."knowledge_base',
                'ordering': ['kategori', 'urutan_prioritas'],
            },
        ),
        migrations.CreateModel(
            name='SesiChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('nama_tamu', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('tgl_mulai', models.DateTimeField(auto_now_add=True)),
                ('tgl_terakhir', models.DateTimeField(auto_now=True)),
                ('total_pesan', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('selesai', 'Selesai'), ('eskalasi', 'Eskalasi ke Manusia')], default='aktif', max_length=10)),
                ('eskalasi_ke_manusia', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesi Chat',
                'verbose_name_plural': 'Sesi Chat',
                'db_table': 'pmb"."sesi_chat',
                'ordering': ['-tgl_mulai'],
            },
        ),
        migrations.CreateModel(
            name='RiwayatChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pengirim', models.CharField(choices=[('user', 'User'), ('bot', 'Bot / AI')], max_length=5)),
                ('pesan', models.TextField()),
                ('sumber_jawaban', models.CharField(blank=True, choices=[('knowledge_base', 'Knowledge Base'), ('ai', 'Claude AI'), ('fallback', 'Fallback')], max_length=15)),
                ('tgl_kirim', models.DateTimeField(auto_now_add=True)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('knowledge_base', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatbot.knowledgebase')),
                ('sesi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesan', to='chatbot.sesichat')),
            ],
            options={
                'verbose_name': 'Riwayat Chat',
                'verbose_name_plural': 'Riwayat Chat',
                'db_table': 'pmb"."riwayat_chat',
                'ordering': ['tgl_kirim'],
            },
        ),
    ]
