# Generated by Django 6.0.4 on 2026-04-20 01:01

import django.db.models.deletion
import django.utils.timezone
import pembayaran.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pendaftaran', '0007_alter_profilpendaftar_sumber_informasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RekeningTujuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_bank', models.CharField(help_text='Contoh: BRI, BNI, Mandiri, BSI', max_length=50)),
                ('no_rekening', models.CharField(max_length=30)),
                ('atas_nama', models.CharField(help_text="Nama pemilik rekening (biasanya 'Universitas Ichsan Gorontalo')", max_length=100)),
                ('cabang', models.CharField(blank=True, max_length=100)),
                ('logo_bank', models.ImageField(blank=True, help_text='Logo bank untuk tampilan (opsional)', null=True, upload_to='rekening/')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan tampil — semakin kecil semakin atas')),
                ('aktif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rekening Tujuan',
                'verbose_name_plural': 'Rekening Tujuan',
                'ordering': ['urutan', 'nama_bank'],
            },
        ),
        migrations.CreateModel(
            name='Tagihan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis', models.CharField(choices=[('biaya_pendaftaran', 'Biaya Pendaftaran'), ('daftar_ulang', 'Daftar Ulang'), ('ukt', 'UKT / SPP')], default='biaya_pendaftaran', max_length=30)),
                ('jumlah', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tgl_tagihan', models.DateField(default=django.utils.timezone.now)),
                ('tgl_jatuh_tempo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('menunggu_konfirmasi', 'Menunggu Konfirmasi'), ('lunas', 'Lunas'), ('expired', 'Expired'), ('dibatalkan', 'Dibatalkan')], db_index=True, default='belum_bayar', max_length=25)),
                ('kode_bayar', models.CharField(db_index=True, default=pembayaran.models.generate_kode_bayar, editable=False, max_length=30, unique=True)),
                ('catatan', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagihan', to='pendaftaran.pendaftaran')),
            ],
            options={
                'verbose_name': 'Tagihan',
                'verbose_name_plural': 'Tagihan',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KonfirmasiPembayaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metode_bayar', models.CharField(choices=[('transfer_bank', 'Transfer Bank'), ('tunai', 'Tunai (Kasir PMB)'), ('qris', 'QRIS')], default='transfer_bank', max_length=20)),
                ('bank_asal', models.CharField(blank=True, help_text='Bank pengirim (contoh: BCA, SeaBank)', max_length=50)),
                ('atas_nama_pengirim', models.CharField(blank=True, max_length=100)),
                ('jumlah_bayar', models.DecimalField(decimal_places=0, max_digits=12)),
                ('tgl_bayar', models.DateField(help_text='Tanggal transfer dilakukan')),
                ('bukti_bayar', models.ImageField(upload_to='bukti_bayar/%Y/%m/')),
                ('no_transaksi', models.CharField(blank=True, help_text='Nomor referensi bank (opsional)', max_length=100)),
                ('status', models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('dikonfirmasi', 'Dikonfirmasi'), ('ditolak', 'Ditolak')], db_index=True, default='menunggu', max_length=15)),
                ('catatan_pengirim', models.TextField(blank=True, help_text='Catatan dari maba')),
                ('catatan_admin', models.TextField(blank=True, help_text='Catatan admin saat verifikasi/tolak')),
                ('tgl_konfirmasi', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dikonfirmasi_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pembayaran_diverifikasi', to=settings.AUTH_USER_MODEL)),
                ('rekening_tujuan', models.ForeignKey(blank=True, help_text='Rekening tujuan yang dipilih maba saat transfer', null=True, on_delete=django.db.models.deletion.SET_NULL, to='pembayaran.rekeningtujuan')),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='konfirmasi', to='pembayaran.tagihan')),
            ],
            options={
                'verbose_name': 'Konfirmasi Pembayaran',
                'verbose_name_plural': 'Konfirmasi Pembayaran',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tagihan',
            index=models.Index(fields=['pendaftaran', 'status'], name='pembayaran__pendaft_94d06b_idx'),
        ),
    ]
