# Generated by Django 6.0.4 on 2026-04-20 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiDuitku',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_order_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100)),
                ('payment_method', models.CharField(max_length=10)),
                ('payment_url', models.URLField(blank=True, max_length=500)),
                ('va_number', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='pending', max_length=15)),
                ('signature', models.CharField(blank=True, max_length=100)),
                ('callback_payload', models.JSONField(blank=True, null=True)),
                ('tgl_paid', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tagihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaksi_duitku', to='pembayaran.tagihan')),
            ],
            options={
                'verbose_name': 'Transaksi Duitku',
                'verbose_name_plural': 'Transaksi Duitku',
                'ordering': ['-created_at'],
            },
        ),
    ]
