# Generated by Django 6.0.4 on 2026-04-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0002_transaksiduitku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagihan',
            name='status',
            field=models.CharField(choices=[('belum_bayar', 'Belum Bayar'), ('menunggu_pembayaran', 'Menunggu Pembayaran (Gateway)'), ('menunggu_konfirmasi', 'Menunggu Konfirmasi Admin'), ('lunas', 'Lunas'), ('expired', 'Expired'), ('dibatalkan', 'Dibatalkan')], db_index=True, default='belum_bayar', max_length=25),
        ),
    ]
