# Generated by Django 6.0.4 on 2026-05-01 15:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_remove_gelombangpenerimaan_nama_bendahara_pmb_and_more'),
        ('pembayaran', '0003_alter_tagihan_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KodeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_voucher', models.CharField(help_text='Kode unik voucher (huruf besar). Contoh: MERDEKA100, EARLY50, ALUMNI25', max_length=20, unique=True)),
                ('jenis_diskon', models.CharField(choices=[('persen', 'Persen (%)'), ('nominal', 'Nominal (Rp)')], default='persen', max_length=10)),
                ('nilai_diskon', models.DecimalField(decimal_places=2, help_text='Untuk persen: 0-100. Untuk nominal: rupiah (mis. 50000)', max_digits=10)),
                ('berlaku_dari', models.DateField(help_text='Tanggal mulai voucher berlaku')),
                ('berlaku_sampai', models.DateField(help_text='Tanggal terakhir voucher berlaku')),
                ('max_penggunaan', models.PositiveIntegerField(default=0, help_text='Batas total pemakaian (0 = tidak terbatas)')),
                ('sudah_dipakai', models.PositiveIntegerField(default=0, help_text='Counter otomatis. Jangan diubah manual.')),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('keterangan', models.TextField(blank=True, help_text='Catatan internal (opsional)')),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
                ('tgl_diupdate', models.DateTimeField(auto_now=True)),
                ('dibuat_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_dibuat', to=settings.AUTH_USER_MODEL)),
                ('jalur', models.ForeignKey(blank=True, help_text='Kosongkan = berlaku untuk semua jalur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voucher_list', to='master.jalurpenerimaan')),
            ],
            options={
                'verbose_name': 'Kode Voucher',
                'verbose_name_plural': 'Kode Voucher',
                'ordering': ['-tgl_dibuat'],
            },
        ),
    ]
