# Generated by Django 6.0.4 on 2026-05-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pembayaran', '0004_kodevoucher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='konfirmasipembayaran',
            name='bukti_bayar',
            field=models.ImageField(blank=True, null=True, upload_to='bukti_bayar/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='konfirmasipembayaran',
            name='metode_bayar',
            field=models.CharField(choices=[('transfer_bank', 'Transfer Bank'), ('tunai', 'Tunai (Kasir PMB)'), ('qris', 'QRIS'), ('voucher', 'Voucher / Diskon')], default='transfer_bank', max_length=20),
        ),
    ]
