# Generated by Django 6.0.4 on 2026-04-16 02:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JalurPenerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_jalur', models.CharField(max_length=10, unique=True)),
                ('nama_jalur', models.CharField(max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('syarat_umum', models.TextField(blank=True)),
                ('ada_tes', models.BooleanField(default=False)),
                ('ada_wawancara', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('urutan', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Jalur Penerimaan',
                'verbose_name_plural': 'Jalur Penerimaan',
                'db_table': 'pmb"."jalur_penerimaan',
                'ordering': ['urutan', 'nama_jalur'],
            },
        ),
        migrations.CreateModel(
            name='PengaturanSistem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tahun_akademik_aktif', models.CharField(default='2025/2026', max_length=10)),
                ('nama_rektor', models.CharField(blank=True, max_length=200)),
                ('nama_wakil_rektor', models.CharField(blank=True, max_length=200)),
                ('no_telepon_pmb', models.CharField(blank=True, max_length=20)),
                ('email_pmb', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_pmb', models.CharField(blank=True, max_length=20)),
                ('alamat_kampus', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='pengaturan/')),
                ('banner_utama', models.ImageField(blank=True, null=True, upload_to='pengaturan/')),
                ('teks_sambutan', models.TextField(blank=True)),
                ('status_pendaftaran', models.CharField(choices=[('buka', 'Buka'), ('tutup', 'Tutup')], default='buka', max_length=5)),
                ('link_wa_group', models.URLField(blank=True)),
                ('nama_wa_group', models.CharField(blank=True, max_length=100)),
                ('deskripsi_wa_group', models.TextField(blank=True)),
                ('tampilkan_wa', models.BooleanField(default=True)),
                ('duitku_merchant_code', models.CharField(blank=True, max_length=50)),
                ('duitku_api_key', models.CharField(blank=True, max_length=100)),
                ('duitku_sandbox', models.BooleanField(default=True)),
                ('nama_rekening', models.CharField(blank=True, max_length=200)),
                ('bank_rekening', models.CharField(blank=True, max_length=50)),
                ('no_rekening', models.CharField(blank=True, max_length=50)),
                ('atas_nama', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Pengaturan Sistem',
                'verbose_name_plural': 'Pengaturan Sistem',
                'db_table': 'pmb"."pengaturan_sistem',
            },
        ),
        migrations.CreateModel(
            name='GelombangPenerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_gelombang', models.CharField(max_length=50)),
                ('tahun_akademik', models.CharField(max_length=10)),
                ('tgl_buka', models.DateField()),
                ('tgl_tutup', models.DateField()),
                ('tgl_seleksi', models.DateField(blank=True, null=True)),
                ('tgl_pengumuman', models.DateField(blank=True, null=True)),
                ('tgl_daftar_ulang', models.DateField(blank=True, null=True)),
                ('jenis_biaya', models.CharField(choices=[('gratis', 'Gratis'), ('potongan', 'Potongan'), ('full', 'Full / Normal')], default='full', max_length=10)),
                ('biaya_penuh', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('persen_potongan', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('nominal_potongan', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('biaya_akhir', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('keterangan_biaya', models.TextField(blank=True)),
                ('berlaku_sampai', models.DateField(blank=True, null=True)),
                ('kuota_total', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('belum_buka', 'Belum Dibuka'), ('buka', 'Dibuka'), ('ditutup', 'Ditutup'), ('selesai', 'Selesai')], default='belum_buka', max_length=15)),
                ('keterangan', models.TextField(blank=True)),
                ('jalur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gelombang', to='master.jalurpenerimaan')),
            ],
            options={
                'verbose_name': 'Gelombang Penerimaan',
                'verbose_name_plural': 'Gelombang Penerimaan',
                'db_table': 'pmb"."gelombang_penerimaan',
                'ordering': ['tahun_akademik', 'jalur', 'nama_gelombang'],
            },
        ),
        migrations.CreateModel(
            name='PersyaratanJalur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_dokumen', models.CharField(max_length=200)),
                ('keterangan', models.TextField(blank=True)),
                ('wajib', models.BooleanField(default=True)),
                ('format_file', models.CharField(choices=[('PDF', 'PDF'), ('JPG', 'JPG / JPEG'), ('PNG', 'PNG'), ('PDF_IMG', 'PDF / JPG / PNG')], default='PDF_IMG', max_length=10)),
                ('ukuran_max', models.IntegerField(default=5, help_text='Ukuran maksimal dalam MB')),
                ('urutan', models.IntegerField(default=0)),
                ('jalur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persyaratan', to='master.jalurpenerimaan')),
            ],
            options={
                'verbose_name': 'Persyaratan Jalur',
                'verbose_name_plural': 'Persyaratan Jalur',
                'db_table': 'pmb"."persyaratan_jalur',
                'ordering': ['jalur', 'urutan'],
            },
        ),
        migrations.CreateModel(
            name='ProdiPMB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_prodi', models.CharField(max_length=10)),
                ('nama_prodi', models.CharField(max_length=200)),
                ('kode_fakultas', models.CharField(max_length=10)),
                ('nama_fakultas', models.CharField(max_length=200)),
                ('kuota', models.IntegerField(default=0)),
                ('daya_tampung', models.IntegerField(default=0)),
                ('biaya_kuliah', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('biaya_spp', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif')], default='aktif', max_length=10)),
                ('gelombang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodi_pmb', to='master.gelombangpenerimaan')),
            ],
            options={
                'verbose_name': 'Prodi PMB',
                'verbose_name_plural': 'Prodi PMB',
                'db_table': 'pmb"."prodi_pmb',
                'ordering': ['kode_fakultas', 'nama_prodi'],
                'unique_together': {('kode_prodi', 'gelombang')},
            },
        ),
    ]
