# Generated by Django 6.0.4 on 2026-04-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jalurpenerimaan',
            name='icon',
            field=models.CharField(default='ti-school', help_text='Nama icon Tabler (contoh: ti-school, ti-pencil, ti-star, ti-trophy)', max_length=50, verbose_name='Icon'),
        ),
        migrations.AddField(
            model_name='jalurpenerimaan',
            name='warna',
            field=models.CharField(choices=[('purple', 'Ungu'), ('blue', 'Biru'), ('green', 'Hijau'), ('red', 'Merah'), ('orange', 'Oranye'), ('teal', 'Teal'), ('pink', 'Pink'), ('indigo', 'Indigo')], default='purple', help_text='Warna gradient icon jalur', max_length=20, verbose_name='Warna Tampilan'),
        ),
    ]
