# Generated by Django 6.0.4 on 2026-04-20 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_jalurpenerimaan_icon_jalurpenerimaan_warna'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelombangpenerimaan',
            name='nama_bendahara_pmb',
            field=models.CharField(blank=True, help_text='Nama lengkap dengan gelar — untuk TTD kwitansi pembayaran', max_length=200),
        ),
        migrations.AddField(
            model_name='gelombangpenerimaan',
            name='nama_ketua_pmb',
            field=models.CharField(blank=True, help_text='Nama lengkap dengan gelar — untuk TTD dokumen resmi (SK, undangan, dll)', max_length=200),
        ),
        migrations.AddField(
            model_name='gelombangpenerimaan',
            name='nip_bendahara_pmb',
            field=models.CharField(blank=True, help_text='NIP / NIDN / ID identitas', max_length=30),
        ),
        migrations.AddField(
            model_name='gelombangpenerimaan',
            name='nip_ketua_pmb',
            field=models.CharField(blank=True, help_text='NIP / NIDN / ID identitas', max_length=30),
        ),
        migrations.AddField(
            model_name='gelombangpenerimaan',
            name='ttd_bendahara_pmb',
            field=models.ImageField(blank=True, help_text='PNG transparan untuk TTD digital, max 1 MB', null=True, upload_to='ttd/'),
        ),
        migrations.AddField(
            model_name='gelombangpenerimaan',
            name='ttd_ketua_pmb',
            field=models.ImageField(blank=True, help_text='PNG transparan untuk TTD digital, max 1 MB', null=True, upload_to='ttd/'),
        ),
    ]
