# Generated by Django 6.0.4 on 2026-04-16 03:08

import django.db.models.deletion
import pendaftaran.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pendaftaran', models.CharField(default=pendaftaran.models.generate_no_pendaftaran, max_length=30, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('LENGKAP', 'Lengkap'), ('DIVERIFIKASI', 'Diverifikasi'), ('LULUS_ADM', 'Lulus Administrasi'), ('TIDAK_LULUS_ADM', 'Tidak Lulus Administrasi'), ('TERJADWAL', 'Terjadwal Seleksi'), ('LULUS_SELEKSI', 'Lulus Seleksi'), ('TIDAK_LULUS', 'Tidak Lulus'), ('DAFTAR_ULANG', 'Daftar Ulang'), ('AKTIF', 'Aktif Mahasiswa'), ('MENGUNDURKAN_DIRI', 'Mengundurkan Diri')], default='DRAFT', max_length=20)),
                ('kode_referral', models.CharField(blank=True, max_length=20)),
                ('kode_voucher', models.CharField(blank=True, max_length=20)),
                ('tgl_daftar', models.DateTimeField(auto_now_add=True)),
                ('tgl_diupdate', models.DateTimeField(auto_now=True)),
                ('gelombang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.gelombangpenerimaan')),
                ('jalur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='master.jalurpenerimaan')),
                ('prodi_pilihan_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pilihan_1', to='master.prodipmb')),
                ('prodi_pilihan_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pilihan_2', to='master.prodipmb')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pendaftaran', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pendaftaran',
                'verbose_name_plural': 'Pendaftaran',
                'db_table': 'pmb"."pendaftaran',
                'ordering': ['-tgl_daftar'],
            },
        ),
        migrations.CreateModel(
            name='LogStatusPendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_lama', models.CharField(blank=True, max_length=20)),
                ('status_baru', models.CharField(max_length=20)),
                ('keterangan', models.TextField(blank=True)),
                ('tgl_perubahan', models.DateTimeField(auto_now_add=True)),
                ('diubah_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_status', to='pendaftaran.pendaftaran')),
            ],
            options={
                'verbose_name': 'Log Status Pendaftaran',
                'verbose_name_plural': 'Log Status Pendaftaran',
                'db_table': 'pmb"."log_status_pendaftaran',
                'ordering': ['-tgl_perubahan'],
            },
        ),
        migrations.CreateModel(
            name='ProfilPendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(blank=True, max_length=16)),
                ('tempat_lahir', models.CharField(blank=True, max_length=100)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('jenis_kelamin', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('agama', models.CharField(blank=True, choices=[('Islam', 'Islam'), ('Kristen', 'Kristen'), ('Katolik', 'Katolik'), ('Hindu', 'Hindu'), ('Buddha', 'Buddha'), ('Konghucu', 'Konghucu')], max_length=10)),
                ('kewarganegaraan', models.CharField(choices=[('WNI', 'WNI'), ('WNA', 'WNA')], default='WNI', max_length=3)),
                ('status_nikah', models.CharField(choices=[('belum_menikah', 'Belum Menikah'), ('menikah', 'Menikah')], default='belum_menikah', max_length=15)),
                ('kebutuhan_khusus', models.CharField(blank=True, help_text='Isi jika difabel', max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='foto_pendaftar/')),
                ('alamat_lengkap', models.TextField(blank=True)),
                ('provinsi', models.CharField(blank=True, max_length=100)),
                ('kabupaten_kota', models.CharField(blank=True, max_length=100)),
                ('kecamatan', models.CharField(blank=True, max_length=100)),
                ('kelurahan', models.CharField(blank=True, max_length=100)),
                ('kode_pos', models.CharField(blank=True, max_length=10)),
                ('nama_ayah', models.CharField(blank=True, max_length=200)),
                ('pekerjaan_ayah', models.CharField(blank=True, max_length=100)),
                ('penghasilan_ayah', models.CharField(blank=True, max_length=20)),
                ('nama_ibu', models.CharField(blank=True, max_length=200)),
                ('pekerjaan_ibu', models.CharField(blank=True, max_length=100)),
                ('penghasilan_ibu', models.CharField(blank=True, max_length=20)),
                ('nama_wali', models.CharField(blank=True, max_length=200)),
                ('no_hp_ortu', models.CharField(blank=True, max_length=20)),
                ('alamat_ortu', models.TextField(blank=True)),
                ('asal_sekolah', models.CharField(blank=True, max_length=200)),
                ('jurusan_sekolah', models.CharField(blank=True, max_length=100)),
                ('tahun_lulus', models.IntegerField(blank=True, null=True)),
                ('no_ijazah', models.CharField(blank=True, max_length=100)),
                ('nilai_rata_rata', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('prestasi', models.TextField(blank=True)),
                ('tgl_diupdate', models.DateTimeField(auto_now=True)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to='pendaftaran.pendaftaran')),
            ],
            options={
                'verbose_name': 'Profil Pendaftar',
                'verbose_name_plural': 'Profil Pendaftar',
                'db_table': 'pmb"."profil_pendaftar',
            },
        ),
        migrations.CreateModel(
            name='TokenAktivasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
                ('sudah_aktif', models.BooleanField(default=False)),
                ('tgl_aktif', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='token_aktivasi', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token Aktivasi',
                'verbose_name_plural': 'Token Aktivasi',
                'db_table': 'pmb"."token_aktivasi',
            },
        ),
    ]
