# Generated by Django 6.0.4 on 2026-04-16 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profilpendaftar',
            old_name='kabupaten_kota',
            new_name='kabupaten_kota_nama',
        ),
        migrations.RenameField(
            model_name='profilpendaftar',
            old_name='kecamatan',
            new_name='kecamatan_nama',
        ),
        migrations.RenameField(
            model_name='profilpendaftar',
            old_name='provinsi',
            new_name='provinsi_nama',
        ),
        migrations.RemoveField(
            model_name='profilpendaftar',
            name='agama',
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='agama_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='agama_nama',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='jurusan_id',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='kabupaten_kota_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='kecamatan_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='npsn',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='provinsi_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='sekolah_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='sumber_informasi',
            field=models.CharField(blank=True, choices=[('website', 'Website PMB UNISAN'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp / Grup WA'), ('teman', 'Info dari Teman / Keluarga'), ('guru', 'Info dari Guru / Sekolah'), ('panitia', 'Konseling Langsung Panitia'), ('brosur', 'Brosur / Flyer'), ('spanduk', 'Spanduk / Banner'), ('recruiter', 'Recruiter / Referral'), ('lainnya', 'Lainnya')], max_length=20),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='sumber_informasi_lain',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='profilpendaftar',
            name='jurusan_sekolah',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
