# Generated by Django 6.0.4 on 2026-04-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0002_rename_kabupaten_kota_profilpendaftar_kabupaten_kota_nama_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilpendaftar',
            name='kebutuhan_khusus',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
