# Generated by Django 6.0.4 on 2026-04-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0003_alter_profilpendaftar_kebutuhan_khusus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpendaftar',
            name='ukuran_baju',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('3XL', '3XL')], help_text='Ukuran baju untuk kebutuhan almamater/seragam', max_length=5),
        ),
    ]
