# Generated by Django 6.0.4 on 2026-04-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0004_profilpendaftar_ukuran_baju'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpendaftar',
            name='no_hp_ayah',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='No HP Ayah'),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='no_hp_ibu',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='No HP Ibu'),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='pendidikan_ayah',
            field=models.CharField(blank=True, choices=[('SD', 'SD / Sederajat'), ('SMP', 'SMP / Sederajat'), ('SMA', 'SMA / SMK / Sederajat'), ('D3', 'Diploma (D1/D2/D3)'), ('D4', 'D4 / Sarjana Terapan'), ('S1', 'S1 / Sarjana'), ('S2', 'S2 / Magister'), ('S3', 'S3 / Doktor'), ('TIDAK_SEKOLAH', 'Tidak Sekolah')], default='', max_length=20, verbose_name='Pendidikan Terakhir Ayah'),
        ),
        migrations.AddField(
            model_name='profilpendaftar',
            name='pendidikan_ibu',
            field=models.CharField(blank=True, choices=[('SD', 'SD / Sederajat'), ('SMP', 'SMP / Sederajat'), ('SMA', 'SMA / SMK / Sederajat'), ('D3', 'Diploma (D1/D2/D3)'), ('D4', 'D4 / Sarjana Terapan'), ('S1', 'S1 / Sarjana'), ('S2', 'S2 / Magister'), ('S3', 'S3 / Doktor'), ('TIDAK_SEKOLAH', 'Tidak Sekolah')], default='', max_length=20, verbose_name='Pendidikan Terakhir Ibu'),
        ),
    ]
