# Generated by Django 6.0.4 on 2026-04-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0005_profilpendaftar_no_hp_ayah_profilpendaftar_no_hp_ibu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilpendaftar',
            name='status_masuk',
            field=models.CharField(choices=[('PDB', 'Penerimaan Mahasiswa Baru'), ('PINDAHAN', 'Mahasiswa Pindahan')], default='PDB', max_length=10, verbose_name='Status Masuk'),
        ),
    ]
