# Generated by Django 6.0.4 on 2026-04-19 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0006_profilpendaftar_status_masuk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilpendaftar',
            name='sumber_informasi',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
