# Generated by Django 6.0.4 on 2026-04-30 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0007_alter_profilpendaftar_sumber_informasi'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEditDataPendaftar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text='Nama field di database, mis: nik, tempat_lahir', max_length=100, verbose_name='Field yang Diubah')),
                ('field_label', models.CharField(blank=True, help_text='Label display, mis: "Nomor Induk Kependudukan"', max_length=200, verbose_name='Label Field')),
                ('old_value', models.TextField(blank=True, verbose_name='Nilai Sebelum')),
                ('new_value', models.TextField(blank=True, verbose_name='Nilai Sesudah')),
                ('alasan', models.TextField(help_text='Wajib diisi. Contoh: "Koreksi tipo nama sesuai ijazah"', verbose_name='Alasan Edit')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address Operator')),
                ('tgl_edit', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Edit')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_pendaftar_logs', to=settings.AUTH_USER_MODEL, verbose_name='Diedit Oleh')),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_edit', to='pendaftaran.pendaftaran', verbose_name='Pendaftaran')),
            ],
            options={
                'verbose_name': 'Log Edit Data Pendaftar',
                'verbose_name_plural': 'Log Edit Data Pendaftar',
                'db_table': 'pmb"."log_edit_data_pendaftar',
                'ordering': ['-tgl_edit'],
            },
        ),
    ]
