# Generated by Django 6.0.4 on 2026-05-01 02:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0008_logeditdatapendaftar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pendaftaran',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendaftar_dihapus', to=settings.AUTH_USER_MODEL, verbose_name='Dihapus Oleh'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='deleted_reason',
            field=models.TextField(blank=True, default='', verbose_name='Alasan Penghapusan'),
        ),
        migrations.AddField(
            model_name='pendaftaran',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
