# Generated by Django 6.0.4 on 2026-05-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0009_pendaftaran_deleted_at_pendaftaran_deleted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('GRATIS_VOUCHER', 'Gratis dengan Voucher'), ('LENGKAP', 'Lengkap'), ('DIVERIFIKASI', 'Diverifikasi'), ('LULUS_ADM', 'Lulus Administrasi'), ('TIDAK_LULUS_ADM', 'Tidak Lulus Administrasi'), ('TERJADWAL', 'Terjadwal Seleksi'), ('LULUS_SELEKSI', 'Lulus Seleksi'), ('TIDAK_LULUS', 'Tidak Lulus'), ('DAFTAR_ULANG', 'Daftar Ulang'), ('AKTIF', 'Aktif Mahasiswa'), ('MENGUNDURKAN_DIRI', 'Mengundurkan Diri')], default='DRAFT', max_length=20),
        ),
    ]
