# Generated by Django 6.0.4 on 2026-04-16 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pendaftaran', '0003_alter_profilpendaftar_kebutuhan_khusus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PengaturanAfiliasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komisi_level_1', models.DecimalField(decimal_places=2, default=50000, max_digits=10)),
                ('komisi_level_2', models.DecimalField(decimal_places=2, default=75000, max_digits=10)),
                ('komisi_level_3', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('komisi_level_4', models.DecimalField(decimal_places=2, default=150000, max_digits=10)),
                ('min_pencairan', models.DecimalField(decimal_places=2, default=100000, max_digits=10)),
                ('syarat_naik_level_2', models.IntegerField(default=5, help_text='Jumlah referral untuk naik ke level 2')),
                ('syarat_naik_level_3', models.IntegerField(default=15, help_text='Jumlah referral untuk naik ke level 3')),
                ('syarat_naik_level_4', models.IntegerField(default=30, help_text='Jumlah referral untuk naik ke level 4')),
                ('aktif', models.BooleanField(default=True)),
                ('deskripsi_program', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Pengaturan Afiliasi',
                'db_table': 'pmb"."pengaturan_afiliasi',
            },
        ),
        migrations.CreateModel(
            name='Recruiter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_referral', models.CharField(max_length=20, unique=True)),
                ('level', models.IntegerField(choices=[(1, 'Level 1 — Recruiter'), (2, 'Level 2 — Senior Recruiter'), (3, 'Level 3 — Master Recruiter'), (4, 'Level 4 — Diamond Recruiter')], default=1)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('suspend', 'Suspend')], default='aktif', max_length=10)),
                ('bank', models.CharField(blank=True, max_length=50)),
                ('no_rekening', models.CharField(blank=True, max_length=30)),
                ('nama_rekening', models.CharField(blank=True, max_length=100)),
                ('total_referral', models.IntegerField(default=0)),
                ('total_komisi', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tgl_bergabung', models.DateTimeField(auto_now_add=True)),
                ('catatan', models.TextField(blank=True)),
                ('rekruiter_induk', models.ForeignKey(blank=True, help_text='Recruiter yang merekrut recruiter ini', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline', to='afiliasi.recruiter')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recruiter',
                'verbose_name_plural': 'Recruiter',
                'db_table': 'pmb"."recruiter',
            },
        ),
        migrations.CreateModel(
            name='PencairanKomisi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bank', models.CharField(max_length=50)),
                ('no_rekening', models.CharField(max_length=30)),
                ('nama_rekening', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('proses', 'Diproses'), ('selesai', 'Selesai'), ('gagal', 'Gagal')], default='pending', max_length=10)),
                ('tgl_request', models.DateTimeField(auto_now_add=True)),
                ('tgl_proses', models.DateTimeField(blank=True, null=True)),
                ('bukti_transfer', models.ImageField(blank=True, null=True, upload_to='bukti_transfer/')),
                ('catatan', models.TextField(blank=True)),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pencairan_diproses', to=settings.AUTH_USER_MODEL)),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pencairan', to='afiliasi.recruiter')),
            ],
            options={
                'verbose_name': 'Pencairan Komisi',
                'verbose_name_plural': 'Pencairan Komisi',
                'db_table': 'pmb"."pencairan_komisi',
            },
        ),
        migrations.CreateModel(
            name='KomisiReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah_komisi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Menunggu Verifikasi'), ('approved', 'Disetujui'), ('paid', 'Sudah Dibayar'), ('rejected', 'Ditolak')], default='pending', max_length=10)),
                ('tgl_komisi', models.DateTimeField(auto_now_add=True)),
                ('tgl_approved', models.DateTimeField(blank=True, null=True)),
                ('tgl_paid', models.DateTimeField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('keterangan_tolak', models.TextField(blank=True)),
                ('diproses_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='komisi_diproses', to=settings.AUTH_USER_MODEL)),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komisi', to='pendaftaran.pendaftaran')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='komisi', to='afiliasi.recruiter')),
            ],
            options={
                'verbose_name': 'Komisi Referral',
                'verbose_name_plural': 'Komisi Referral',
                'db_table': 'pmb"."komisi_referral',
            },
        ),
    ]
