# Generated by Django 6.0.4 on 2026-04-17 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='status',
            field=models.CharField(choices=[('menunggu', 'Menunggu Verifikasi'), ('aktif', 'Aktif'), ('nonaktif', 'Nonaktif'), ('suspend', 'Suspend')], default='menunggu', max_length=10),
        ),
    ]
