# Generated by Django 6.0.4 on 2026-04-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliasi', '0002_alter_recruiter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='foto_ktp',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter/ktp/'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='foto_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter/selfie/'),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='pekerjaan',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
