# Generated by Django 6.0.4 on 2026-04-21 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliasi', '0003_recruiter_foto_ktp_recruiter_foto_selfie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KontenFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_periode', models.CharField(help_text="Contoh: 'PMB 2026/2027 Gelombang 1'", max_length=100)),
                ('tahun_akademik', models.CharField(default='2026/2027', max_length=20)),
                ('headline_utama', models.CharField(default='Masa Depanmu Dimulai di Sini', help_text='Judul besar di flyer. Max 80 karakter.', max_length=80)),
                ('sub_headline', models.CharField(default='7 Fakultas - 16 Program Studi - Terakreditasi BAN-PT', help_text='Teks kedua di bawah headline. Max 120 karakter.', max_length=120)),
                ('cta_text', models.CharField(default='Daftar Sekarang', help_text='Teks tombol call-to-action', max_length=60)),
                ('jumlah_fakultas', models.PositiveIntegerField(default=7)),
                ('jumlah_prodi', models.PositiveIntegerField(default=16)),
                ('jalur_tersedia', models.CharField(default='Reguler - Undangan - Beasiswa - RPL - Pindahan', max_length=120)),
                ('warna_primer', models.CharField(default='#3C3489', help_text='Warna utama gradient. Format: #RRGGBB', max_length=7)),
                ('warna_sekunder', models.CharField(default='#534AB7', help_text='Warna kedua gradient. Format: #RRGGBB', max_length=7)),
                ('warna_aksen', models.CharField(default='#7F77DD', help_text='Warna aksen (lingkaran dekorasi). Format: #RRGGBB', max_length=7)),
                ('website_display', models.CharField(default='pmb.unisan.ac.id', max_length=60)),
                ('nomor_wa_pmb', models.CharField(blank=True, default='', help_text='Opsional. Muncul di flyer jika diisi.', max_length=20)),
                ('is_aktif', models.BooleanField(default=True, help_text='Hanya SATU konten yang boleh aktif pada satu waktu')),
                ('dibuat_pada', models.DateTimeField(auto_now_add=True)),
                ('diubah_pada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Konten Flyer',
                'verbose_name_plural': 'Konten Flyer',
                'db_table': 'pmb"."konten_flyer',
                'ordering': ['-is_aktif', '-diubah_pada'],
            },
        ),
        migrations.CreateModel(
            name='TemplateFlyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(choices=[('story', 'Story / Reels (1080x1920)'), ('feed', 'Feed Post (1080x1080)'), ('cetak', 'Flyer Cetak (1200x1800)'), ('banner', 'Banner Landscape (1920x1080)')], max_length=10, unique=True)),
                ('nama', models.CharField(max_length=60)),
                ('deskripsi', models.TextField(blank=True, help_text='Untuk kebutuhan apa template ini cocok dipakai')),
                ('width', models.PositiveIntegerField(help_text='Lebar dalam pixel')),
                ('height', models.PositiveIntegerField(help_text='Tinggi dalam pixel')),
                ('is_aktif', models.BooleanField(default=True, help_text='Nonaktifkan jika template tidak ingin ditampilkan ke recruiter')),
                ('urutan', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Template Flyer',
                'verbose_name_plural': 'Template Flyer',
                'db_table': 'pmb"."template_flyer',
                'ordering': ['urutan', 'kode'],
            },
        ),
    ]
