# Generated by Django 6.0.4 on 2026-04-17 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('master', '0001_initial'),
        ('pendaftaran', '0004_profilpendaftar_ukuran_baju'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HasilPenerimaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('lulus', 'Lulus'), ('tidak_lulus', 'Tidak Lulus'), ('cadangan', 'Cadangan'), ('lulus_bersyarat', 'Lulus Bersyarat')], max_length=20)),
                ('nilai_akhir', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('peringkat', models.IntegerField(blank=True, null=True)),
                ('catatan', models.TextField(blank=True)),
                ('tgl_pengumuman', models.DateField(blank=True, null=True)),
                ('sudah_daftar_ulang', models.BooleanField(default=False)),
                ('tgl_daftar_ulang', models.DateTimeField(blank=True, null=True)),
                ('tgl_diinput', models.DateTimeField(auto_now_add=True)),
                ('diinput_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil', to='pendaftaran.pendaftaran')),
                ('prodi_diterima', models.ForeignKey(help_text='Prodi yang diterima (bisa berbeda dari pilihan 1)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='master.prodipmb')),
            ],
            options={
                'verbose_name': 'Hasil Penerimaan',
                'verbose_name_plural': 'Hasil Penerimaan',
                'db_table': 'pmb"."hasil_penerimaan',
                'ordering': ['peringkat', 'nilai_akhir'],
            },
        ),
        migrations.CreateModel(
            name='JadwalSeleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jenis_seleksi', models.CharField(choices=[('tes_tulis', 'Tes Tulis'), ('wawancara', 'Wawancara'), ('tes_praktik', 'Tes Praktik'), ('portofolio', 'Review Portofolio'), ('administrasi', 'Seleksi Administrasi')], max_length=15)),
                ('nama_seleksi', models.CharField(max_length=200)),
                ('tgl_seleksi', models.DateField()),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('lokasi', models.CharField(blank=True, max_length=200)),
                ('link_online', models.URLField(blank=True, help_text='Link Zoom/Meet jika online')),
                ('keterangan', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('publish', 'Dipublikasi'), ('selesai', 'Selesai'), ('batal', 'Dibatalkan')], default='draft', max_length=10)),
                ('tgl_dibuat', models.DateTimeField(auto_now_add=True)),
                ('dibuat_oleh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('gelombang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.gelombangpenerimaan')),
                ('jalur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master.jalurpenerimaan')),
            ],
            options={
                'verbose_name': 'Jadwal Seleksi',
                'verbose_name_plural': 'Jadwal Seleksi',
                'db_table': 'pmb"."jadwal_seleksi',
                'ordering': ['tgl_seleksi', 'jam_mulai'],
            },
        ),
        migrations.CreateModel(
            name='KartuPeserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_kartu', models.CharField(max_length=30, unique=True)),
                ('tgl_cetak', models.DateTimeField(auto_now_add=True)),
                ('sudah_cetak', models.BooleanField(default=False)),
                ('pendaftaran', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kartu', to='pendaftaran.pendaftaran')),
            ],
            options={
                'verbose_name': 'Kartu Peserta',
                'db_table': 'pmb"."kartu_peserta',
            },
        ),
        migrations.CreateModel(
            name='PesertaSeleksi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_ujian', models.CharField(blank=True, max_length=20)),
                ('status_kehadiran', models.CharField(choices=[('terdaftar', 'Terdaftar'), ('hadir', 'Hadir'), ('tidak_hadir', 'Tidak Hadir'), ('izin', 'Izin')], default='terdaftar', max_length=15)),
                ('nilai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('catatan_penilai', models.TextField(blank=True)),
                ('tgl_penilaian', models.DateTimeField(blank=True, null=True)),
                ('dinilai_oleh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='penilaian', to=settings.AUTH_USER_MODEL)),
                ('jadwal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peserta', to='seleksi.jadwalseleksi')),
                ('pendaftaran', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seleksi', to='pendaftaran.pendaftaran')),
            ],
            options={
                'verbose_name': 'Peserta Seleksi',
                'verbose_name_plural': 'Peserta Seleksi',
                'db_table': 'pmb"."peserta_seleksi',
                'unique_together': {('jadwal', 'pendaftaran')},
            },
        ),
    ]
